# Generated by Django 3.1.7 on 2021-04-12 20:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
